services:
  paperai:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    volumes:
      - ..:/work
    working_dir: /work
    environment:
      - PYTHONPATH=/work/paperai/src/python
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - ../.env
    tty: true
    stdin_open: true